--DB: Nerdbook ; user: stefano ; pass: stefano ;


CREATE TABLE utentiRegistratiType (
    idUtentiRegistratiType INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32)
);

CREATE TABLE utentiRegistrati (
    idUtentiRegistrati  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256),
    cognome VARCHAR(256),
    password VARCHAR(256) NOT NULL,
    urlAvatar VARCHAR(256),
    data VARCHAR(256),
    email VARCHAR(256) UNIQUE,
    frase VARCHAR(2048),
    type INTEGER,
    FOREIGN KEY (type) REFERENCES utentiRegistratiType(idUtentiRegistratiType)
);

CREATE TABLE posts (
    idPosts  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1024),
    image VARCHAR(512),
    link VARCHAR(512),
    urlVideo VARCHAR(512),
    author INTEGER,
    FOREIGN KEY (author) REFERENCES utentiRegistrati(idUtentiRegistrati),
    bacheca INTEGER,
    bachecaGruppi INTEGER
);

CREATE TABLE gruppi (
    idGruppi  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(1024),
    image VARCHAR(512)
        
);

CREATE TABLE amici (
   follower INTEGER,
   FOREIGN KEY (follower) REFERENCES utentiRegistrati(idUtentiRegistrati),
   followed INTEGER,
   FOREIGN KEY (followed) REFERENCES utentiRegistrati(idUtentiRegistrati),
   PRIMARY KEY (follower, followed)
);

CREATE TABLE followergruppi (
   followed INTEGER,
   FOREIGN KEY (followed) REFERENCES gruppi(idGruppi),
   follower INTEGER,
   FOREIGN KEY (follower) REFERENCES utentiRegistrati(idUtentiRegistrati),
   PRIMARY KEY (followed, follower)
);


--Popolamento tabella utentiRegistratiType
INSERT INTO utentiRegistratiType (idUtentiRegistratiType, name)
VALUES (default, 'NORMAL');

INSERT INTO utentiRegistratiType (idUtentiRegistratiType, name)
VALUES (default, 'ADMIN');


--Popolamento tabella utentiRegistrati


INSERT INTO utentiRegistrati (idUtentiRegistrati, nome, cognome, password, urlAvatar, data, email, frase, type)
VALUES (default,
        'Admin',
        'istrator',
        '123456',
        'img/mario_face.jpg',
        '25/12/0000',
        'admin@gmail.com',
        'ma che bella frase',
        2
    );

INSERT INTO utentiRegistrati (idUtentiRegistrati, nome, cognome, password, urlAvatar, data, email, frase, type)
VALUES (default,
        'Giovanni',
        'Rodriguez',
        '123456',
        'img/avatar-placeholder.jpg',
        '25/12/0000',
        'giovannirodriguez@gmail.com',
        'ma che bella frase',
        1
    );

INSERT INTO utentiRegistrati (idUtentiRegistrati, nome, cognome, password, urlAvatar, data, email, frase, type)
VALUES (default,
        'Marco',
        'Bianco',
        '123456',
        'img/avatar-placeholder.jpg',
        '25/12/0000',
        'marcobianco@gmail.com',
        'ma che bella frase',
        1
    );

INSERT INTO utentiRegistrati (idUtentiRegistrati, nome, cognome, password, urlAvatar, data, email, frase, type)
VALUES (default,
        'Reginaldo',
        'Rossi',
        '123456',
        'img/avatar-placeholder.jpg',
        '25/12/0000',
        'reginaldorossi@gmail.com',
        'ma che bella frase',
        1
    );

INSERT INTO utentiRegistrati (idUtentiRegistrati, nome, cognome, password, urlAvatar, data, email, frase, type)
VALUES (default,
        'Mario',
        'Bross',
        '123456',
        'img/mario_face.jpg',
        '25/12/0000',
        'mariobross@gmail.com',
        'ma che bella frase',
        1
    );

INSERT INTO utentiRegistrati (idUtentiRegistrati, nome, cognome, password, urlAvatar, data, email, frase, type)
VALUES (default,
        'Marco',
        'Pinco',
        '123456',
        'img/mario_face.jpg',
        '25/12/0000',
        'marcopinco@gmail.com',
        'ma che bella frase',
        1
    );


--Popolamento tabella gruppi
INSERT INTO gruppi (idGruppi, nome, image)
VALUES (default,
        'Giochi di Ruolo',
        ''
    );

INSERT INTO gruppi (idGruppi, nome, image)
VALUES (default,
        'Fotografia',
        ''
    );

INSERT INTO gruppi (idGruppi, nome, image)
VALUES (default,
        'AMM/PW',
        ''
    );

--Popolamento tabella Post
INSERT INTO posts (idPosts, content, image, link, urlVideo, author, bacheca, bachecaGruppi)
VALUES (default,
        'trallalero trallala che cosa si scriverà?',
        '',
        '',
        '',
        2,
        2,
        null
        );

INSERT INTO posts (idPosts, content, image, link, urlVideo, author, bacheca, bachecaGruppi)
VALUES (default,
        'Divvertente questa immagine di pack Man',
        'img/b0979598-c427-4f71-b235-51e4c733753d.jpg',
        '',
        '',
        3,
        3,
        null
        );

INSERT INTO posts (idPosts, content, image, link, urlVideo, author, bacheca, bachecaGruppi)
VALUES (default,
        'Simpatica la descrizione del minus world',
        '',
        'https://it.wikipedia.org/wiki/Super_Mario_Bros.',
        '',
        4,
        4,
        null
        );

INSERT INTO posts (idPosts, content, image, link, urlVideo, author, bacheca, bachecaGruppi)
VALUES (default,
        'we we bello sto video!!',
        '',
        '',
        'https://www.youtube.com/embed/-Khe61uso_o',
        5,
        5,
        null
        );

INSERT INTO posts (idPosts, content, image, link, urlVideo, author, bacheca, bachecaGruppi)
VALUES (default,
        'Che bello quando funzionano le cose e diventi subito contento',
        'img/b0979598-c427-4f71-b235-51e4c733753d.jpg',
        '',
        '',
        5,
        5,
        null
        );

INSERT INTO posts (idPosts, content, image, link, urlVideo, author, bacheca, bachecaGruppi)
VALUES (default,
        'Il nuovo video di Coez',
        '',
        '',
        'https://www.youtube.com/embed/zVzER12pk4o',
        6,
        6,
        null
        );

INSERT INTO posts (idPosts, content, image, link, urlVideo, author, bacheca, bachecaGruppi)
VALUES (default,
        'Il nuovo video di Coez',
        '',
        '',
        'https://www.youtube.com/embed/zVzER12pk4o',
        6,
        null,
        1
        );

INSERT INTO amici (follower, followed)
VALUES (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (2, 1),
       (2, 3),
       (2, 4),
       (2, 5),
       (2, 6),
       (3, 1),
       (3, 2),
       (3, 4),
       (3, 5),
       (3, 6),
       (4, 1),
       (4, 2),
       (4, 3),
       (4, 5),
       (4, 6),
       (5, 1),
       (5, 2),
       (5, 3),
       (5, 4),
       (5, 6),
       (6, 1),
       (6, 2),
       (6, 3),
       (6, 4),
       (6, 5);



INSERT INTO followergruppi (followed, follower)
VALUES (1, 2),
       (1, 3),
       (1, 6),
       (2, 2),
       (2, 3),
       (2, 4),
       (2, 5),
       (3, 3),
       (3, 4),
       (3, 2);